name: dynamic_table
description: A fully customized data table for your flutter project in which you can edit, delete, add and update values in the table.
version: 0.0.1-beta.2
homepage: https://github.com/aakash-pamnani/dynamic_table
repository: https://github.com/aakash-pamnani/dynamic_table
issue_tracker: https://github.com/aakash-pamnani/dynamic_table/issues

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
