name: dynamic_table
description: A fully customized data table for your flutter project in which you can edit, delete, add and update values in the table./nIt is build upon [PaginatedDataTable](https://api.flutter.dev/flutter/material/PaginatedDataTable-class.html)
version: 0.0.1
homepage: https://github.com/aakash-pamnani/dynamic_table
repository: https://github.com/aakash-pamnani/dynamic_table
issue_tracker: https://github.com/aakash-pamnani/dynamic_table/issues

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
